version: "3.7"
services:
  prod-application-server:
    container_name: web-application-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../logs:/var/log/application-logs
    network_mode: host

  develop-application-server:
    container_name: web-application-server
    build:
      context: .
      dockerfile: Dockerfile-Develop
    volumes:
      - ../../logs:/var/log/application-logs
    network_mode: host
