spring:
  profiles:
    active: local
  flyway:
    baseline-on-migrate: true
    baseline-version: 20210802223415
  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 15MB
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 1000

security:
  jwt:
    access-token:
      secret-key: JFJNuw3Mjy_7Q%j5d4u9*-GqnQyLxu
      expire-length: 86400000 # 1일
    refresh-token:
      secret-key: qppwnflnr15158Gqgnelfnwk213
      expire-length: 5184000000 # 60일

oauth:
  kakao:
    client-id: 184b32bf5a62bf7c6887cdb48f9c432b
    client-secret: 25nCjDgamZgbTQLllMNcxOSFbe7z0VLW
    authorization-server-url: https://kauth.kakao.com/oauth/token
    api-server-url: https://kapi.kakao.com/v2/user/me
  naver:
    client-id: s_uLGFZxls7jgZtsjBlW
    client-secret: rxJkUdyv3t
    authorization-server-url: https://nid.naver.com/oauth2.0/token
    api-server-url: https://openapi.naver.com/v1/nid/me
  github:
    client-id: 96f270ce3e0af33e8075
    client-secret: 470fd0775463bf507847f704c63d8d57a67aaf88
    authorization-server-url: https://github.com/login/oauth/access_token
    api-server-url: https://api.github.com/user

server:
  compression:
    enabled: true

stomp-broker:
    ip: 52.78.66.216
    port: 8000
    username: username
    password: password
