spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/darass-prod
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: develop
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
  slack:
    webhook-uri: /services/T0280M8QMGT/B02BEFE2C8G/MM1BveGzKk8DQhXbfj5czkx1

cookie:
  same-site: None
