# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Dev-Darass Push Builder [BE]

on:
  push:
    branches: [ main ]

jobs:
  dev-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_REPO_PAT }}
        submodules: recursive

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Seoul

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./backend

    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: ./backend
      
    - name: Copy built project
      if: success()
      uses: appleboy/scp-action@master
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      with:
        host: ${{ secrets.NCP_ACCESS_HOST }}
        username: ${{ secrets.NCP_USERNAME }}
        port: ${{ secrets.NCP_PORT }}
        password: ${{ secrets.NCP_PASSWORD }}
        envs: GIT_USERNAME, GIT_PASSWORD
        source: '.'
        target: '/root/application/darass-backend'
        strip_components: 1

    - name: AWS EC2에 ssh로 접속해서 scripts 실행시키기
      if: success()
      uses: appleboy/ssh-action@master
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      with:
        host: ${{ secrets.NCP_ACCESS_HOST }}
        username: ${{ secrets.NCP_USERNAME }}
        port: ${{ secrets.NCP_PORT }}
        password: ${{ secrets.NCP_PASSWORD }}
        envs: GIT_USERNAME, GIT_PASSWORD
        script: |
          cd /root/application/darass-backend/backend/dev
          docker-compose up --build -d
          
    - name: build result to slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
